language: android
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - build-tools-28.0.3
    - android-28

before_install:
  - chmod +x gradlew

install:
  - ./gradlew clean :coconut:testDebug