sudo: false
language: android

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-28.0.3
    - android-28


before_install:
  - chmod +x gradlew
  # Install the rest of tools (e.g., avdmanager)
  - yes | sdkmanager tools
  # Install the system image
  - yes | sdkmanager "system-images;android-18;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install:
  - ./gradlew build connectedCheck
  - ./gradlew clean :coconut:test

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache